In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("final_data_with_individual features.csv")
df

,Unnamed: 0,Unnamed: 0.1,ID,SEASON,CITY,CITY_Corrrected,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,...,TOSS_DECISION,RESULT,WINNER,WIN_BY_RUNS,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
0,0,0,60,2008,Bangalore,RCB,KKR,1,RCB,0,...,field,normal,KKR,140,0,1,0,0,0.000000,0.000000
1,1,1,61,2008,Chandigarh,KXIP,CSK,1,KXIP,0,...,bat,normal,CSK,33,1,1,1,0,0.000000,0.000000
2,2,2,62,2008,Delhi,DD,DD,1,RR,0,...,bat,normal,DD,0,0,1,1,1,0.000000,0.000000
3,3,3,63,2008,Mumbai,MI,RCB,1,MI,0,...,bat,normal,RCB,0,0,1,1,0,0.000000,0.000000
4,4,4,64,2008,Kolkata,KKR,KKR,1,SRH,0,...,bat,normal,KKR,0,0,1,1,1,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,742,742,11346,2019,Mohali,KXIP,CSK,1,KXIP,0,...,field,normal,KXIP,0,0,0,0,0,0.622642,0.465517
743,743,743,11347,2019,Mumbai,MI,KKR,1,MI,0,...,field,normal,MI,0,0,0,0,0,0.519774,0.576087
744,744,744,11412,2019,Chennai,CSK,CSK,1,MI,0,...,bat,normal,MI,0,1,0,1,1,0.618750,0.578378
745,745,745,11413,2019,Visakhapatnam,Visakhapatnam,SRH,1,DD,0,...,field,normal,DD,0,0,0,0,2,0.478022,0.432749
746,746,746,11414,2019,Visakhapatnam,Visakhapatnam,DD,1,CSK,0,...,field,normal,CSK,0,0,0,0,2,0.436047,0.614907

In [3]:
df.dropna().drop(["Unnamed: 0", "Unnamed: 0.1", "ID", "TEAM1", "TEAM2", "CITY", "TOSS_DECISION", "WIN_BY_RUNS", "CITY_Corrrected", "TOSS_WINNER", "WINNER"], axis=1, inplace=True)
df

C:\Users\khand\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Unnamed: 0,Unnamed: 0.1,ID,SEASON,CITY,CITY_Corrrected,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,...,TOSS_DECISION,RESULT,WINNER,WIN_BY_RUNS,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
0,0,0,60,2008,Bangalore,RCB,KKR,1,RCB,0,...,field,normal,KKR,140,0,1,0,0,0.000000,0.000000
1,1,1,61,2008,Chandigarh,KXIP,CSK,1,KXIP,0,...,bat,normal,CSK,33,1,1,1,0,0.000000,0.000000
2,2,2,62,2008,Delhi,DD,DD,1,RR,0,...,bat,normal,DD,0,0,1,1,1,0.000000,0.000000
3,3,3,63,2008,Mumbai,MI,RCB,1,MI,0,...,bat,normal,RCB,0,0,1,1,0,0.000000,0.000000
4,4,4,64,2008,Kolkata,KKR,KKR,1,SRH,0,...,bat,normal,KKR,0,0,1,1,1,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,742,742,11346,2019,Mohali,KXIP,CSK,1,KXIP,0,...,field,normal,KXIP,0,0,0,0,0,0.622642,0.465517
743,743,743,11347,2019,Mumbai,MI,KKR,1,MI,0,...,field,normal,MI,0,0,0,0,0,0.519774,0.576087
744,744,744,11412,2019,Chennai,CSK,CSK,1,MI,0,...,bat,normal,MI,0,1,0,1,1,0.618750,0.578378
745,745,745,11413,2019,Visakhapatnam,Visakhapatnam,SRH,1,DD,0,...,field,normal,DD,0,0,0,0,2,0.478022,0.432749
746,746,746,11414,2019,Visakhapatnam,Visakhapatnam,DD,1,CSK,0,...,field,normal,CSK,0,0,0,0,2,0.436047,0.614907

In [4]:
df.drop(["Unnamed: 0", "Unnamed: 0.1", "ID", "TEAM1", "TEAM2", "CITY", "TOSS_DECISION", "WIN_BY_RUNS", "CITY_Corrrected", "TOSS_WINNER", "WINNER"], axis=1, inplace=True)
df

,SEASON,TEAM1_MODEL,TEAM2_MODEL,TEAM1_RunsperOver,TEAM1_RunsperWicket,TEAM1_BattingIndex,TEAM1_RunsconcededperOver,TEAM1_RunsconcededperWicket,TEAM1_BowlingIndex,TEAM1_BattingWicketRate,...,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,RESULT,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
0,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,normal,0,1,0,0,0.000000,0.000000
1,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,normal,1,1,1,0,0.000000,0.000000
2,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,normal,0,1,1,1,0.000000,0.000000
3,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,normal,0,1,1,0,0.000000,0.000000
4,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,normal,0,1,1,1,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,2019,1,0,8.578696,35.038961,300.588607,8.619450,30.200000,260.307400,0.040806,...,322.237674,313.604762,310.114484,normal,0,0,0,0,0.622642,0.465517
743,2019,1,0,8.536977,25.776699,220.055099,8.947253,29.500000,263.943956,0.055198,...,246.504167,334.660714,296.831463,normal,0,0,0,0,0.519774,0.576087
744,2019,1,0,8.578696,35.038961,300.588607,8.619450,30.200000,260.307400,0.040806,...,322.237674,334.660714,296.831463,normal,1,0,1,1,0.618750,0.578378
745,2019,1,0,7.796102,26.530612,206.835358,7.892377,28.085106,221.658239,0.048976,...,229.800840,317.250000,278.938492,normal,0,0,0,2,0.478022,0.432749
746,2019,1,0,8.720930,30.000000,261.627907,8.922299,31.386667,280.041238,0.048450,...,278.938492,275.301136,322.237674,normal,0,0,0,2,0.436047,0.614907

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 747 entries, 0 to 746
Data columns (total 54 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   SEASON                              747 non-null    int64
 1   TEAM1_MODEL                         747 non-null    int64
 2   TEAM2_MODEL                         747 non-null    int64
 3   TEAM1_RunsperOver                   670 non-null    float64
 4   TEAM1_RunsperWicket                 670 non-null    float64
 5   TEAM1_BattingIndex                  670 non-null    float64
 6   TEAM1_RunsconcededperOver           670 non-null    float64
 7   TEAM1_RunsconcededperWicket         670 non-null    float64
 8   TEAM1_BowlingIndex                  670 non-null    float64
 9   TEAM1_BattingWicketRate             670 non-null    float64
 10  TEAM1_BowlingWicketRate             670 non-null    float64
 11  TEAM1_RunsperWicket_6Batsmen        689 non-null    float64
 12  TEAM1_RunsperWicket_4Batsmen        689 non-null    float64
 13  TEAM1_RunsperWicket_2Batsmen        689 non-null    float64
 14  TEAM1_Runsperball_6Batsmen          689 non-null    float64
 15  TEAM1_Runsperball_4Batsmen          689 non-null    float64
 16  TEAM1_Runsperball_2Batsmen          689 non-null    float64
 17  TEAM1_RunsconcedeperWicket_5Bowler  689 non-null    float64
 18  TEAM1_RunsconcedeperWicket_3Bowler  689 non-null    float64
 19  TEAM1_RunsconcedeperOver_5Bowler    689 non-null    float64
 20  TEAM1_RunsconcedeperOver_3Bowler    689 non-null    float64
 21  TEAM1_BallsbowledperWicket_5Bowler  689 non-null    float64
 22  TEAM1_BallsbowledperWicket_3Bowler  689 non-null    float64
 23  TEAM2_RunsperOver                   665 non-null    float64
 24  TEAM2_RunsperWicket                 665 non-null    float64
 25  TEAM2_BattingIndex                  665 non-null    float64
 26  TEAM2_RunsconcededperOver           665 non-null    float64
 27  TEAM2_RunsconcededperWicket         665 non-null    float64
 28  TEAM2_BowlingIndex                  665 non-null    float64
 29  TEAM2_BattingWicketRate             665 non-null    float64
 30  TEAM2_BowlingWicketRate             665 non-null    float64
 31  TEAM2_RunsperWicket_6Batsmen        689 non-null    float64
 32  TEAM2_RunsperWicket_4Batsmen        689 non-null    float64
 33  TEAM2_RunsperWicket_2Batsmen        689 non-null    float64
 34  TEAM2_Runsperball_6Batsmen          689 non-null    float64
 35  TEAM2_Runsperball_4Batsmen          689 non-null    float64
 36  TEAM2_Runsperball_2Batsmen          689 non-null    float64
 37  TEAM2_RunsconcedeperWicket_5Bowler  689 non-null    float64
 38  TEAM2_RunsconcedeperWicket_3Bowler  689 non-null    float64
 39  TEAM2_RunsconcedeperOver_5Bowler    689 non-null    float64
 40  TEAM2_RunsconcedeperOver_3Bowler    689 non-null    float64
 41  TEAM2_BallsbowledperWicket_5Bowler  689 non-null    float64
 42  TEAM2_BallsbowledperWicket_3Bowler  689 non-null    float64
 43  TEAM1_STRENGTH                      649 non-null    float64
 44  TEAM1_CUMU_STRENGTH                 649 non-null    float64
 45  TEAM2_STRENGTH                      641 non-null    float64
 46  TEAM2_CUMU_STRENGTH                 641 non-null    float64
 47  RESULT                              747 non-null    object
 48  TOSS_WINNER_MODEL                   747 non-null    int64
 49  WINNER_MODEL                        747 non-null    int64
 50  TOSS_DECISION_MODEL                 747 non-null    int64
 51  CITY_MODEL                          747 non-null    int64
 52  WIN_RATE_TEAM1                      747 non-null    float64
 53  WIN_RATE_TEAM2                      747 non-null    float64
dtypes: float64(46), int64(7), object(1)
memory usage: 315.3+ KB

In [6]:
df['RESULT'] = df['RESULT'].map({'normal': 1, 'tie': 0})
df

,SEASON,TEAM1_MODEL,TEAM2_MODEL,TEAM1_RunsperOver,TEAM1_RunsperWicket,TEAM1_BattingIndex,TEAM1_RunsconcededperOver,TEAM1_RunsconcededperWicket,TEAM1_BowlingIndex,TEAM1_BattingWicketRate,...,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,RESULT,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
0,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,0,1,0,0,0.000000,0.000000
1,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,1,1,1,0,0.000000,0.000000
2,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,0,1,1,1,0.000000,0.000000
3,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,0,1,1,0,0.000000,0.000000
4,2008,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,0,1,1,1,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,2019,1,0,8.578696,35.038961,300.588607,8.619450,30.200000,260.307400,0.040806,...,322.237674,313.604762,310.114484,1,0,0,0,0,0.622642,0.465517
743,2019,1,0,8.536977,25.776699,220.055099,8.947253,29.500000,263.943956,0.055198,...,246.504167,334.660714,296.831463,1,0,0,0,0,0.519774,0.576087
744,2019,1,0,8.578696,35.038961,300.588607,8.619450,30.200000,260.307400,0.040806,...,322.237674,334.660714,296.831463,1,1,0,1,1,0.618750,0.578378
745,2019,1,0,7.796102,26.530612,206.835358,7.892377,28.085106,221.658239,0.048976,...,229.800840,317.250000,278.938492,1,0,0,0,2,0.478022,0.432749
746,2019,1,0,8.720930,30.000000,261.627907,8.922299,31.386667,280.041238,0.048450,...,278.938492,275.301136,322.237674,1,0,0,0,2,0.436047,0.614907

In [7]:
df.dropna(axis=0, inplace=True)
df

,SEASON,TEAM1_MODEL,TEAM2_MODEL,TEAM1_RunsperOver,TEAM1_RunsperWicket,TEAM1_BattingIndex,TEAM1_RunsconcededperOver,TEAM1_RunsconcededperWicket,TEAM1_BowlingIndex,TEAM1_BattingWicketRate,...,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,RESULT,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
58,2009,1,0,7.542744,24.012658,181.121323,7.873077,24.662651,194.170945,0.052353,...,336.799423,260.997520,260.997520,1,0,1,0,2,0.500000,0.562500
59,2009,1,0,6.971963,17.594340,122.667078,8.191205,38.250000,313.313576,0.066044,...,281.718151,251.393601,251.393601,1,1,1,1,2,0.285714,0.812500
60,2009,1,0,8.337292,29.620253,246.952705,8.356890,28.493976,238.121035,0.046912,...,233.565387,305.110606,305.110606,1,0,0,0,2,0.666667,0.500000
61,2009,1,0,7.199201,20.465909,147.338184,7.767188,27.163934,210.987372,0.058628,...,224.529054,251.854847,251.854847,1,1,0,1,2,0.461538,0.142857
62,2009,1,0,7.874584,29.936709,235.739122,8.197922,30.108434,246.826602,0.043840,...,260.997520,281.718151,281.718151,1,1,1,1,2,0.529412,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,2019,1,0,8.578696,35.038961,300.588607,8.619450,30.200000,260.307400,0.040806,...,322.237674,313.604762,310.114484,1,0,0,0,0,0.622642,0.465517
743,2019,1,0,8.536977,25.776699,220.055099,8.947253,29.500000,263.943956,0.055198,...,246.504167,334.660714,296.831463,1,0,0,0,0,0.519774,0.576087
744,2019,1,0,8.578696,35.038961,300.588607,8.619450,30.200000,260.307400,0.040806,...,322.237674,334.660714,296.831463,1,1,0,1,1,0.618750,0.578378
745,2019,1,0,7.796102,26.530612,206.835358,7.892377,28.085106,221.658239,0.048976,...,229.800840,317.250000,278.938492,1,0,0,0,2,0.478022,0.432749
746,2019,1,0,8.720930,30.000000,261.627907,8.922299,31.386667,280.041238,0.048450,...,278.938492,275.301136,322.237674,1,0,0,0,2,0.436047,0.614907

In [8]:
X = df.drop("WINNER_MODEL", axis=1)
y = df["WINNER_MODEL"]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=12)

In [10]:
# pip install mlxtend

In [11]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
from sklearn.ensemble import RandomForestClassifier

In [12]:
efs1 = EFS(RandomForestClassifier(n_estimators=100, max_depth=5,random_state=0), 
           min_features=1,
           max_features=46,
           scoring='accuracy',
           print_progress=True,
           cv=None,
          n_jobs = -1).fit(X_train, y_train)

KeyboardInterrupt: