In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# Dataset 1 without Multiplying Innings

## Dataset 1- Modelling 1

In [2]:
df = pd.read_csv("final_model_data_V3New.csv")
df

,Unnamed: 0,Unnamed: 0.1,ID,SEASON,CITY,CITY_Corrrected,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,...,TOSS_DECISION,RESULT,WINNER,WIN_BY_RUNS,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
0,0,0,60,2008,Bangalore,RCB,KKR,1,RCB,0,...,field,normal,KKR,140,0,1,0,0,0.000000,0.000000
1,1,1,61,2008,Chandigarh,KXIP,CSK,1,KXIP,0,...,bat,normal,CSK,33,1,1,1,0,0.000000,0.000000
2,2,2,62,2008,Delhi,DD,DD,1,RR,0,...,bat,normal,DD,0,0,1,1,1,0.000000,0.000000
3,3,3,63,2008,Mumbai,MI,RCB,1,MI,0,...,bat,normal,RCB,0,0,1,1,0,0.000000,0.000000
4,4,4,64,2008,Kolkata,KKR,KKR,1,SRH,0,...,bat,normal,KKR,0,0,1,1,1,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,742,742,11346,2019,Mohali,KXIP,CSK,1,KXIP,0,...,field,normal,KXIP,0,0,0,0,0,0.622642,0.465517
743,743,743,11347,2019,Mumbai,MI,KKR,1,MI,0,...,field,normal,MI,0,0,0,0,0,0.519774,0.576087
744,744,744,11412,2019,Chennai,CSK,CSK,1,MI,0,...,bat,normal,MI,0,1,0,1,1,0.618750,0.578378
745,745,745,11413,2019,Visakhapatnam,Visakhapatnam,SRH,1,DD,0,...,field,normal,DD,0,0,0,0,2,0.478022,0.432749
746,746,746,11414,2019,Visakhapatnam,Visakhapatnam,DD,1,CSK,0,...,field,normal,CSK,0,0,0,0,2,0.436047,0.614907

In [3]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'ID', 'SEASON', 'CITY', 'CITY_Corrrected',
       'TEAM1', 'TEAM1_MODEL', 'TEAM2', 'TEAM2_MODEL', 'TEAM1_STRENGTH',
       'TEAM1_CUMU_STRENGTH', 'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH',
       'TOSS_WINNER', 'TOSS_DECISION', 'RESULT', 'WINNER', 'WIN_BY_RUNS',
       'TOSS_WINNER_MODEL', 'WINNER_MODEL', 'TOSS_DECISION_MODEL',
       'CITY_MODEL', 'WIN_RATE_TEAM1', 'WIN_RATE_TEAM2'],
      dtype='object')

In [4]:
df["TOSS_WINNER"]

0       RCB
1       CSK
2        RR
3        MI
4       SRH
       ...
742    KXIP
743      MI
744     CSK
745      DD
746     CSK
Name: TOSS_WINNER, Length: 747, dtype: object

In [5]:
df.drop(["Unnamed: 0", "Unnamed: 0.1", "ID"], axis=1, inplace = True)
df

,SEASON,CITY,CITY_Corrrected,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,...,TOSS_DECISION,RESULT,WINNER,WIN_BY_RUNS,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
0,2008,Bangalore,RCB,KKR,1,RCB,0,224.529054,224.529054,281.718151,...,field,normal,KKR,140,0,1,0,0,0.000000,0.000000
1,2008,Chandigarh,KXIP,CSK,1,KXIP,0,260.997520,260.997520,233.565387,...,bat,normal,CSK,33,1,1,1,0,0.000000,0.000000
2,2008,Delhi,DD,DD,1,RR,0,305.110606,305.110606,251.393601,...,bat,normal,DD,0,0,1,1,1,0.000000,0.000000
3,2008,Mumbai,MI,RCB,1,MI,0,281.718151,281.718151,336.799423,...,bat,normal,RCB,0,0,1,1,0,0.000000,0.000000
4,2008,Kolkata,KKR,KKR,1,SRH,0,224.529054,224.529054,251.854847,...,bat,normal,KKR,0,0,1,1,1,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,2019,Mohali,KXIP,CSK,1,KXIP,0,322.764706,307.838265,342.142857,...,field,normal,KXIP,0,0,0,0,0,0.622642,0.465517
743,2019,Mumbai,MI,KKR,1,MI,0,406.857143,286.291744,352.763889,...,field,normal,MI,0,0,0,0,0,0.519774,0.576087
744,2019,Chennai,CSK,CSK,1,MI,0,322.764706,307.838265,352.763889,...,bat,normal,MI,0,1,0,1,1,0.618750,0.578378
745,2019,Visakhapatnam,Visakhapatnam,SRH,1,DD,0,384.866667,312.965524,299.568750,...,field,normal,DD,0,0,0,0,2,0.478022,0.432749
746,2019,Visakhapatnam,Visakhapatnam,DD,1,CSK,0,299.568750,256.139205,322.764706,...,field,normal,CSK,0,0,0,0,2,0.436047,0.614907

In [6]:
df = df[["TEAM1", "TEAM1_MODEL", "TEAM2", "TEAM2_MODEL", "TOSS_WINNER", "TOSS_WINNER_MODEL", "TEAM1_STRENGTH", "TEAM1_CUMU_STRENGTH", \
        "TEAM2_STRENGTH", "TEAM2_CUMU_STRENGTH", "WIN_RATE_TEAM1", "WIN_RATE_TEAM2", "WINNER", "WINNER_MODEL"]]

In [7]:
df

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
0,KKR,1,RCB,0,RCB,0,224.529054,224.529054,281.718151,281.718151,0.000000,0.000000,KKR,1
1,CSK,1,KXIP,0,CSK,1,260.997520,260.997520,233.565387,233.565387,0.000000,0.000000,CSK,1
2,DD,1,RR,0,RR,0,305.110606,305.110606,251.393601,251.393601,0.000000,0.000000,DD,1
3,RCB,1,MI,0,MI,0,281.718151,281.718151,336.799423,336.799423,0.000000,0.000000,RCB,1
4,KKR,1,SRH,0,SRH,0,224.529054,224.529054,251.854847,251.854847,1.000000,0.000000,KKR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,322.764706,307.838265,342.142857,279.395125,0.622642,0.465517,KXIP,0
743,KKR,1,MI,0,MI,0,406.857143,286.291744,352.763889,315.820960,0.519774,0.576087,MI,0
744,CSK,1,MI,0,CSK,1,322.764706,307.838265,352.763889,315.820960,0.618750,0.578378,MI,0
745,SRH,1,DD,0,DD,0,384.866667,312.965524,299.568750,256.139205,0.478022,0.432749,DD,0
746,DD,1,CSK,0,CSK,0,299.568750,256.139205,322.764706,307.838265,0.436047,0.614907,CSK,0

In [8]:
df.isna().sum()

TEAM1                  0
TEAM1_MODEL            0
TEAM2                  0
TEAM2_MODEL            0
TOSS_WINNER            0
TOSS_WINNER_MODEL      0
TEAM1_STRENGTH         0
TEAM1_CUMU_STRENGTH    0
TEAM2_STRENGTH         0
TEAM2_CUMU_STRENGTH    0
WIN_RATE_TEAM1         0
WIN_RATE_TEAM2         0
WINNER                 0
WINNER_MODEL           0
dtype: int64

In [9]:
df["TEAM2"]

0       RCB
1      KXIP
2        RR
3        MI
4       SRH
       ...
742    KXIP
743      MI
744      MI
745      DD
746     CSK
Name: TEAM2, Length: 747, dtype: object

In [10]:
df[df["TEAM2"] == "GL"]

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
513,KXIP,1,GL,0,GL,0,299.464286,312.218537,315.323661,283.078125,0.495798,0.000000,GL,0
516,RPS,1,GL,0,RPS,1,310.171995,312.976616,315.323661,283.078125,0.282609,1.000000,GL,0
519,MI,1,GL,0,GL,0,418.339286,394.199405,315.323661,283.078125,0.578125,1.000000,GL,0
529,RCB,1,GL,0,RCB,1,329.187500,274.864955,315.323661,283.078125,0.495935,0.750000,GL,0
535,RPS,1,GL,0,GL,0,310.171995,312.976616,315.323661,283.078125,0.274510,0.833333,GL,0
538,KXIP,1,GL,0,GL,0,299.464286,312.218537,315.323661,283.078125,0.480000,0.857143,KXIP,1
548,KKR,1,GL,0,GL,0,287.116667,281.928571,315.323661,283.078125,0.523810,0.600000,GL,0
554,RCB,1,GL,0,GL,0,329.187500,274.864955,315.323661,283.078125,0.488372,0.636364,RCB,1
561,KKR,1,GL,0,GL,0,287.116667,281.928571,315.323661,283.078125,0.519380,0.583333,GL,0
564,MI,1,GL,0,GL,0,418.339286,394.199405,315.323661,283.078125,0.575540,0.615385,GL,0
573,KKR,1,GL,0,KKR,1,256.156250,259.932192,343.003401,323.978458,0.515152,0.562500,KKR,1
576,SRH,1,GL,0,SRH,1,398.857143,319.876984,343.003401,323.978458,0.463768,0.529412,SRH,1
586,MI,1,GL,0,MI,1,265.660131,304.025210,343.003401,323.978458,0.576389,0.526316,MI,1
590,RCB,1,GL,0,GL,0,399.461539,309.825550,343.003401,323.978458,0.492857,0.500000,RCB,1
596,KXIP,1,GL,0,GL,0,244.214286,268.873016,343.003401,323.978458,0.467626,0.500000,KXIP,1
604,MI,1,GL,0,GL,0,265.660131,304.025210,343.003401,323.978458,0.581081,0.500000,MI,1
608,RPS,1,GL,0,RPS,1,249.546875,249.277951,343.003401,323.978458,0.323529,0.480000,RPS,1
611,DD,1,GL,0,DD,1,272.339286,275.073413,343.003401,323.978458,0.417266,0.461538,DD,1
619,DD,1,GL,0,DD,1,272.339286,275.073413,343.003401,323.978458,0.418440,0.464286,DD,1
622,SRH,1,GL,0,SRH,1,398.857143,319.876984,343.003401,323.978458,0.469799,0.448276,SRH,1

In [11]:
df[df["TEAM1"] == "GL"]

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
525,GL,1,SRH,0,SRH,0,315.323661,283.078125,276.529412,222.247899,1.000000,0.430894,SRH,0
533,GL,1,DD,0,DD,0,315.323661,283.078125,338.857143,303.525000,0.800000,0.425000,GL,1
541,GL,1,DD,0,DD,0,315.323661,283.078125,338.857143,303.525000,0.750000,0.426230,DD,0
544,GL,1,SRH,0,SRH,0,315.323661,283.078125,276.529412,222.247899,0.666667,0.440945,SRH,0
567,GL,1,RCB,0,RCB,0,315.323661,283.078125,329.187500,274.864955,0.642857,0.503759,RCB,0
569,GL,1,SRH,0,SRH,0,315.323661,283.078125,276.529412,222.247899,0.600000,0.451852,SRH,0
583,GL,1,RPS,0,GL,1,343.003401,323.978458,249.546875,249.277951,0.500000,0.290323,GL,1
593,GL,1,KKR,0,GL,1,343.003401,323.978458,256.156250,259.932192,0.476190,0.525547,GL,1
600,GL,1,RCB,0,GL,1,343.003401,323.978458,399.461539,309.825550,0.478261,0.492958,GL,1
616,GL,1,KXIP,0,GL,1,343.003401,323.978458,244.214286,268.873016,0.444444,0.475524,GL,1

In [12]:
df.drop(df[df["TEAM1"] == "KTK"].index, inplace = True) 
df.drop(df[df["TEAM2"] == "KTK"].index, inplace = True) 
df.drop(df[df["TEAM1"] == "GL"].index, inplace = True) 
df.drop(df[df["TEAM2"] == "GL"].index, inplace = True)

C:\Users\khand\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [13]:
df

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
0,KKR,1,RCB,0,RCB,0,224.529054,224.529054,281.718151,281.718151,0.000000,0.000000,KKR,1
1,CSK,1,KXIP,0,CSK,1,260.997520,260.997520,233.565387,233.565387,0.000000,0.000000,CSK,1
2,DD,1,RR,0,RR,0,305.110606,305.110606,251.393601,251.393601,0.000000,0.000000,DD,1
3,RCB,1,MI,0,MI,0,281.718151,281.718151,336.799423,336.799423,0.000000,0.000000,RCB,1
4,KKR,1,SRH,0,SRH,0,224.529054,224.529054,251.854847,251.854847,1.000000,0.000000,KKR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,322.764706,307.838265,342.142857,279.395125,0.622642,0.465517,KXIP,0
743,KKR,1,MI,0,MI,0,406.857143,286.291744,352.763889,315.820960,0.519774,0.576087,MI,0
744,CSK,1,MI,0,CSK,1,322.764706,307.838265,352.763889,315.820960,0.618750,0.578378,MI,0
745,SRH,1,DD,0,DD,0,384.866667,312.965524,299.568750,256.139205,0.478022,0.432749,DD,0
746,DD,1,CSK,0,CSK,0,299.568750,256.139205,322.764706,307.838265,0.436047,0.614907,CSK,0

### Modelling without using AHP

In [14]:
df.columns

Index(['TEAM1', 'TEAM1_MODEL', 'TEAM2', 'TEAM2_MODEL', 'TOSS_WINNER',
       'TOSS_WINNER_MODEL', 'TEAM1_STRENGTH', 'TEAM1_CUMU_STRENGTH',
       'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH', 'WIN_RATE_TEAM1',
       'WIN_RATE_TEAM2', 'WINNER', 'WINNER_MODEL'],
      dtype='object')

In [15]:
X = df[['TEAM1_MODEL', 'TEAM2_MODEL', 
       'TOSS_WINNER_MODEL', 'TEAM1_STRENGTH', 'TEAM1_CUMU_STRENGTH',
       'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH', 'WIN_RATE_TEAM1',
       'WIN_RATE_TEAM2']]
y = df["WINNER_MODEL"]

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=12)

In [17]:
import lazypredict
from lazypredict.Supervised import LazyClassifier

C:\Users\khand\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)

In [18]:
clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 28.89it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
LogisticRegression,0.60,0.61,0.61,0.58,0.02
RidgeClassifierCV,0.59,0.60,0.60,0.58,0.02
LinearSVC,0.58,0.60,0.60,0.57,0.05
LinearDiscriminantAnalysis,0.58,0.60,0.60,0.57,0.02
RidgeClassifier,0.58,0.60,0.60,0.57,0.01
BaggingClassifier,0.59,0.59,0.59,0.59,0.04
CalibratedClassifierCV,0.57,0.59,0.59,0.56,0.10
AdaBoostClassifier,0.57,0.58,0.58,0.57,0.07
XGBClassifier,0.57,0.57,0.57,0.57,0.05
SVC,0.56,0.57,0.57,0.56,0.03
BernoulliNB,0.55,0.56,0.56,0.55,0.02
GaussianNB,0.54,0.56,0.56,0.51,0.00
LGBMClassifier,0.56,0.56,0.56,0.56,0.10
Perceptron,0.55,0.55,0.55,0.55,0.00
NearestCentroid,0.52,0.54,0.54,0.52,0.00
LabelPropagation,0.53,0.54,0.54,0.53,0.03
LabelSpreading,0.53,0.54,0.54,0.53,0.02
RandomForestClassifier,0.52,0.53,0.53,0.53,0.19
ExtraTreesClassifier,0.52,0.53,0.53,0.53,0.13
SGDClassifier,0.53,0.52,0.52,0.53,0.01
PassiveAggressiveClassifier,0.51,0.51,0.51,0.51,0.01
DummyClassifier,0.51,0.51,0.51,0.51,0.02
DecisionTreeClassifier,0.50,0.50,0.50,0.50,0.02
QuadraticDiscriminantAnalysis,0.46,0.50,0.50,0.29,0.02
CheckingClassifier,0.46,0.50,0.50,0.29,0.00
KNeighborsClassifier,0.50,0.50,0.50,0.50,0.02
ExtraTreeClassifier,0.47,0.47,0.47,0.47,0.00
NuSVC,0.45,0.46,0.46,0.45,0.05

### Adding AHP column and modelling using that

RPS 	6.032793\
DD 	    8.076035\
SRH 	9.026536\
KXIP 	9.380131\
RCB 	9.982425\
RR 	    12.695051\
KKR 	12.745465\
MI 	    15.160852\
CSK 	16.900712

In [19]:
df_ahp1 = df
df_ahp1

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
0,KKR,1,RCB,0,RCB,0,224.53,224.53,281.72,281.72,0.00,0.00,KKR,1
1,CSK,1,KXIP,0,CSK,1,261.00,261.00,233.57,233.57,0.00,0.00,CSK,1
2,DD,1,RR,0,RR,0,305.11,305.11,251.39,251.39,0.00,0.00,DD,1
3,RCB,1,MI,0,MI,0,281.72,281.72,336.80,336.80,0.00,0.00,RCB,1
4,KKR,1,SRH,0,SRH,0,224.53,224.53,251.85,251.85,1.00,0.00,KKR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,322.76,307.84,342.14,279.40,0.62,0.47,KXIP,0
743,KKR,1,MI,0,MI,0,406.86,286.29,352.76,315.82,0.52,0.58,MI,0
744,CSK,1,MI,0,CSK,1,322.76,307.84,352.76,315.82,0.62,0.58,MI,0
745,SRH,1,DD,0,DD,0,384.87,312.97,299.57,256.14,0.48,0.43,DD,0
746,DD,1,CSK,0,CSK,0,299.57,256.14,322.76,307.84,0.44,0.61,CSK,0

In [20]:
df_ahp1["AHP_RATIO_TEAM1"] = ''
df_ahp1["AHP_RATIO_TEAM2"] = ''


for i in range(0, 703):
    if df_ahp1["TEAM1"].iloc[i] == "CSK":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 16.900712
    
    elif df_ahp1["TEAM1"].iloc[i] == "MI":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 15.160852
    
    elif df_ahp1["TEAM1"].iloc[i] == "KKR":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 12.745465
    
    elif df_ahp1["TEAM1"].iloc[i] == "RR":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 12.695051
    
    elif df_ahp1["TEAM1"].iloc[i] == "RCB":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 9.982425
    
    elif df_ahp1["TEAM1"].iloc[i] == "KXIP":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 9.380131
    
    elif df_ahp1["TEAM1"].iloc[i] == "SRH":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 9.026536
        
    elif df_ahp1["TEAM1"].iloc[i] == "DD":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 8.076035
    
    elif df_ahp1["TEAM1"].iloc[i] == "RPS":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 6.032793
    
        
for i in range(0, 703):       
    if df_ahp1["TEAM2"].iloc[i] == "CSK":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 16.900712
        
    elif df_ahp1["TEAM2"].iloc[i] == "MI":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 15.160852
        
    elif df_ahp1["TEAM2"].iloc[i] == "KKR":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 12.745465
        
    elif df_ahp1["TEAM2"].iloc[i] == "RR":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 12.695051
        
    elif df_ahp1["TEAM2"].iloc[i] == "RCB":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 9.982425
        
    elif df_ahp1["TEAM2"].iloc[i] == "KXIP":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 9.380131
        
    elif df_ahp1["TEAM2"].iloc[i] == "SRH":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 9.026536
        
    elif df_ahp1["TEAM2"].iloc[i] == "DD":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 8.076035
        
    elif df_ahp1["TEAM2"].iloc[i] == "RPS":
        df_ahp1["AHP_RATIO_TEAM2"].iloc[i] = 6.032793

In [21]:
df_ahp1

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL,AHP_RATIO_TEAM1,AHP_RATIO_TEAM2
0,KKR,1,RCB,0,RCB,0,224.53,224.53,281.72,281.72,0.00,0.00,KKR,1,12.75,9.98
1,CSK,1,KXIP,0,CSK,1,261.00,261.00,233.57,233.57,0.00,0.00,CSK,1,16.90,9.38
2,DD,1,RR,0,RR,0,305.11,305.11,251.39,251.39,0.00,0.00,DD,1,8.08,12.70
3,RCB,1,MI,0,MI,0,281.72,281.72,336.80,336.80,0.00,0.00,RCB,1,9.98,15.16
4,KKR,1,SRH,0,SRH,0,224.53,224.53,251.85,251.85,1.00,0.00,KKR,1,12.75,9.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,322.76,307.84,342.14,279.40,0.62,0.47,KXIP,0,16.90,9.38
743,KKR,1,MI,0,MI,0,406.86,286.29,352.76,315.82,0.52,0.58,MI,0,12.75,15.16
744,CSK,1,MI,0,CSK,1,322.76,307.84,352.76,315.82,0.62,0.58,MI,0,16.90,15.16
745,SRH,1,DD,0,DD,0,384.87,312.97,299.57,256.14,0.48,0.43,DD,0,9.03,8.08
746,DD,1,CSK,0,CSK,0,299.57,256.14,322.76,307.84,0.44,0.61,CSK,0,8.08,16.90

In [22]:
df_ahp1.isna().sum()

TEAM1                  0
TEAM1_MODEL            0
TEAM2                  0
TEAM2_MODEL            0
TOSS_WINNER            0
TOSS_WINNER_MODEL      0
TEAM1_STRENGTH         0
TEAM1_CUMU_STRENGTH    0
TEAM2_STRENGTH         0
TEAM2_CUMU_STRENGTH    0
WIN_RATE_TEAM1         0
WIN_RATE_TEAM2         0
WINNER                 0
WINNER_MODEL           0
AHP_RATIO_TEAM1        0
AHP_RATIO_TEAM2        0
dtype: int64

In [23]:
# df_ahp1.to_csv("no_innings_ahp_column.csv", index=False)

In [24]:
X = df_ahp1[['TEAM1_MODEL', 'TEAM2_MODEL', 
       'TOSS_WINNER_MODEL', 'TEAM1_STRENGTH', 'TEAM1_CUMU_STRENGTH',
       'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH', 'WIN_RATE_TEAM1',
       'WIN_RATE_TEAM2', 'AHP_RATIO_TEAM1', 'AHP_RATIO_TEAM2']]
y = df_ahp1["WINNER_MODEL"]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=12)

In [26]:
clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 21.21it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
ExtraTreesClassifier,0.58,0.59,0.59,0.58,0.16
RidgeClassifierCV,0.57,0.58,0.58,0.57,0.03
LogisticRegression,0.57,0.58,0.58,0.57,0.05
AdaBoostClassifier,0.57,0.58,0.58,0.56,0.10
SVC,0.57,0.58,0.58,0.56,0.02
CalibratedClassifierCV,0.57,0.58,0.58,0.56,0.14
RidgeClassifier,0.57,0.57,0.57,0.57,0.02
LinearDiscriminantAnalysis,0.57,0.57,0.57,0.57,0.02
LinearSVC,0.57,0.57,0.57,0.57,0.07
NearestCentroid,0.55,0.56,0.56,0.55,0.02
ExtraTreeClassifier,0.57,0.56,0.56,0.57,0.02
KNeighborsClassifier,0.56,0.56,0.56,0.56,0.03
BaggingClassifier,0.55,0.55,0.55,0.54,0.05
GaussianNB,0.55,0.55,0.55,0.54,0.02
XGBClassifier,0.54,0.55,0.55,0.53,0.10
NuSVC,0.54,0.54,0.54,0.54,0.04
BernoulliNB,0.53,0.54,0.54,0.53,0.02
SGDClassifier,0.54,0.53,0.53,0.53,0.02
LGBMClassifier,0.53,0.53,0.53,0.53,0.11
PassiveAggressiveClassifier,0.52,0.52,0.52,0.52,0.03
RandomForestClassifier,0.52,0.52,0.52,0.52,0.25
DummyClassifier,0.51,0.51,0.51,0.51,0.00
LabelSpreading,0.50,0.51,0.51,0.50,0.04
LabelPropagation,0.50,0.51,0.51,0.50,0.02
Perceptron,0.50,0.51,0.51,0.50,0.02
CheckingClassifier,0.46,0.50,0.50,0.29,0.00
DecisionTreeClassifier,0.49,0.50,0.50,0.49,0.03
QuadraticDiscriminantAnalysis,0.48,0.49,0.49,0.48,0.02

## Dataset 1- Modelling 2

In [27]:
df_ahp1

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL,AHP_RATIO_TEAM1,AHP_RATIO_TEAM2
0,KKR,1,RCB,0,RCB,0,224.53,224.53,281.72,281.72,0.00,0.00,KKR,1,12.75,9.98
1,CSK,1,KXIP,0,CSK,1,261.00,261.00,233.57,233.57,0.00,0.00,CSK,1,16.90,9.38
2,DD,1,RR,0,RR,0,305.11,305.11,251.39,251.39,0.00,0.00,DD,1,8.08,12.70
3,RCB,1,MI,0,MI,0,281.72,281.72,336.80,336.80,0.00,0.00,RCB,1,9.98,15.16
4,KKR,1,SRH,0,SRH,0,224.53,224.53,251.85,251.85,1.00,0.00,KKR,1,12.75,9.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,322.76,307.84,342.14,279.40,0.62,0.47,KXIP,0,16.90,9.38
743,KKR,1,MI,0,MI,0,406.86,286.29,352.76,315.82,0.52,0.58,MI,0,12.75,15.16
744,CSK,1,MI,0,CSK,1,322.76,307.84,352.76,315.82,0.62,0.58,MI,0,16.90,15.16
745,SRH,1,DD,0,DD,0,384.87,312.97,299.57,256.14,0.48,0.43,DD,0,9.03,8.08
746,DD,1,CSK,0,CSK,0,299.57,256.14,322.76,307.84,0.44,0.61,CSK,0,8.08,16.90

In [28]:
## Divided by the mean.

RPS 	0.542951\
DD 	    0.726843\
SRH 	0.812388\
KXIP 	0.844212\
RCB 	0.898418\
RR 	    1.142555\
KKR 	1.147092\
MI 	    1.364477\
CSK 	1.521064

In [29]:
for i in range(0, 703):
    if df_ahp1["TEAM1"].iloc[i] == "CSK":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 1.521064
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.521064
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 1.521064
    
    elif df_ahp1["TEAM1"].iloc[i] == "MI":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 1.364477
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.364477
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 1.364477
    
    elif df_ahp1["TEAM1"].iloc[i] == "KKR":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 1.147092
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.147092
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 1.147092
    
    elif df_ahp1["TEAM1"].iloc[i] == "RR":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 1.142555
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.142555
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 1.142555
    
    elif df_ahp1["TEAM1"].iloc[i] == "RCB":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 0.898418
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.898418
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 0.898418
    
    elif df_ahp1["TEAM1"].iloc[i] == "KXIP":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 0.844212
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.844212
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 0.844212
    
    elif df_ahp1["TEAM1"].iloc[i] == "SRH":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 0.812388
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.812388
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 0.812388

    elif df_ahp1["TEAM1"].iloc[i] == "DD":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 0.726843
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.726843
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 0.726843
    
    elif df_ahp1["TEAM1"].iloc[i] == "RPS":
        df_ahp1["TEAM1_STRENGTH"].iloc[i] = df_ahp1["TEAM1_STRENGTH"].iloc[i] * 0.542951
        df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.542951
        df_ahp1["WIN_RATE_TEAM1"].iloc[i] = df_ahp1["WIN_RATE_TEAM1"].iloc[i] * 0.542951
        

for i in range(0, 703):
    if df_ahp1["TEAM2"].iloc[i] == "CSK":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 1.521064
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.521064
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 1.521064
    
    elif df_ahp1["TEAM2"].iloc[i] == "MI":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 1.364477
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.364477
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 1.364477
    
    elif df_ahp1["TEAM2"].iloc[i] == "KKR":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 1.147092
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.147092
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 1.147092
    
    elif df_ahp1["TEAM2"].iloc[i] == "RR":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 1.142555
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.142555
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 1.142555
    
    elif df_ahp1["TEAM2"].iloc[i] == "RCB":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 0.898418
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.898418
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 0.898418
    
    elif df_ahp1["TEAM2"].iloc[i] == "KXIP":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 0.844212
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.844212
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 0.844212
    
    elif df_ahp1["TEAM1"].iloc[i] == "SRH":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 0.812388
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.812388
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 0.812388

    elif df_ahp1["TEAM1"].iloc[i] == "DD":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 0.726843
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.726843
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 0.726843
    
    elif df_ahp1["TEAM2"].iloc[i] == "RPS":
        df_ahp1["TEAM2_STRENGTH"].iloc[i] = df_ahp1["TEAM2_STRENGTH"].iloc[i] * 0.542951
        df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp1["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.542951
        df_ahp1["WIN_RATE_TEAM2"].iloc[i] = df_ahp1["WIN_RATE_TEAM2"].iloc[i] * 0.542951

In [30]:
df_ahp1

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL,AHP_RATIO_TEAM1,AHP_RATIO_TEAM2
0,KKR,1,RCB,0,RCB,0,257.56,257.56,253.10,253.10,0.00,0.00,KKR,1,12.75,9.98
1,CSK,1,KXIP,0,CSK,1,396.99,396.99,197.18,197.18,0.00,0.00,CSK,1,16.90,9.38
2,DD,1,RR,0,RR,0,221.77,221.77,287.23,287.23,0.00,0.00,DD,1,8.08,12.70
3,RCB,1,MI,0,MI,0,253.10,253.10,459.56,459.56,0.00,0.00,RCB,1,9.98,15.16
4,KKR,1,SRH,0,SRH,0,257.56,257.56,251.85,251.85,1.15,0.00,KKR,1,12.75,9.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,490.95,468.24,288.84,235.87,0.95,0.39,KXIP,0,16.90,9.38
743,KKR,1,MI,0,MI,0,466.70,328.40,481.34,430.93,0.60,0.79,MI,0,12.75,15.16
744,CSK,1,MI,0,CSK,1,490.95,468.24,481.34,430.93,0.94,0.79,MI,0,16.90,15.16
745,SRH,1,DD,0,DD,0,312.66,254.25,243.37,208.08,0.39,0.35,DD,0,9.03,8.08
746,DD,1,CSK,0,CSK,0,217.74,186.17,490.95,468.24,0.32,0.94,CSK,0,8.08,16.90

In [31]:
# df_ahp1.to_csv("no_innings_ahp_mean.csv", index=False)

In [32]:
X = df[['TEAM1_MODEL', 'TEAM2_MODEL', 
       'TOSS_WINNER_MODEL', 'TEAM1_STRENGTH', 'TEAM1_CUMU_STRENGTH',
       'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH', 'WIN_RATE_TEAM1',
       'WIN_RATE_TEAM2']]
y = df["WINNER_MODEL"]

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=12)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 26.91it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
CalibratedClassifierCV,0.64,0.64,0.64,0.64,0.10
SVC,0.63,0.64,0.64,0.63,0.04
LGBMClassifier,0.63,0.63,0.63,0.63,0.10
RandomForestClassifier,0.62,0.63,0.63,0.62,0.20
LinearDiscriminantAnalysis,0.61,0.62,0.62,0.61,0.02
RidgeClassifier,0.61,0.62,0.62,0.61,0.02
LogisticRegression,0.61,0.62,0.62,0.61,0.02
LinearSVC,0.61,0.62,0.62,0.61,0.05
RidgeClassifierCV,0.61,0.61,0.61,0.61,0.02
XGBClassifier,0.61,0.61,0.61,0.61,0.06
SGDClassifier,0.59,0.61,0.61,0.57,0.00
BaggingClassifier,0.59,0.60,0.60,0.59,0.04
ExtraTreesClassifier,0.57,0.58,0.58,0.57,0.13
Perceptron,0.58,0.58,0.58,0.58,0.02
KNeighborsClassifier,0.57,0.57,0.57,0.58,0.02
BernoulliNB,0.57,0.57,0.57,0.58,0.00
DecisionTreeClassifier,0.57,0.57,0.57,0.57,0.00
NearestCentroid,0.57,0.57,0.57,0.57,0.02
ExtraTreeClassifier,0.57,0.57,0.57,0.57,0.00
GaussianNB,0.57,0.57,0.57,0.57,0.02
LabelPropagation,0.56,0.56,0.56,0.56,0.01
LabelSpreading,0.56,0.56,0.56,0.56,0.03
AdaBoostClassifier,0.56,0.56,0.56,0.56,0.09
NuSVC,0.55,0.54,0.54,0.55,0.07
DummyClassifier,0.51,0.51,0.51,0.51,0.02
CheckingClassifier,0.46,0.50,0.50,0.29,0.02
QuadraticDiscriminantAnalysis,0.46,0.50,0.50,0.29,0.00
PassiveAggressiveClassifier,0.47,0.47,0.47,0.47,0.02

In [33]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [34]:
model.score(X_train, y_train)

1.0

In [35]:
model.score(X_test, y_test)

0.624113475177305

# Dataset 2 with Innings Multiplied

## Dataset 2 - Modelling 1

In [36]:
df = pd.read_csv("strength_by_innings_new.csv")
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,ID,SEASON,CITY,CITY_Corrrected,TEAM1,TEAM1_MODEL,TEAM2,...,TOSS_DECISION,RESULT,WINNER,WIN_BY_RUNS,TOSS_WINNER_MODEL,WINNER_MODEL,TOSS_DECISION_MODEL,CITY_MODEL,WIN_RATE_TEAM1,WIN_RATE_TEAM2
0,0,0,0,60,2008,Bangalore,RCB,KKR,1,RCB,...,field,normal,KKR,140,0,1,0,0,0.00,0.00
1,1,1,1,61,2008,Chandigarh,KXIP,CSK,1,KXIP,...,bat,normal,CSK,33,1,1,1,0,0.00,0.00
2,2,2,2,62,2008,Delhi,DD,DD,1,RR,...,bat,normal,DD,0,0,1,1,1,0.00,0.00
3,3,3,3,63,2008,Mumbai,MI,RCB,1,MI,...,bat,normal,RCB,0,0,1,1,0,0.00,0.00
4,4,4,4,64,2008,Kolkata,KKR,KKR,1,SRH,...,bat,normal,KKR,0,0,1,1,1,1.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,742,742,742,11346,2019,Mohali,KXIP,CSK,1,KXIP,...,field,normal,KXIP,0,0,0,0,0,0.62,0.47
743,743,743,743,11347,2019,Mumbai,MI,KKR,1,MI,...,field,normal,MI,0,0,0,0,0,0.52,0.58
744,744,744,744,11412,2019,Chennai,CSK,CSK,1,MI,...,bat,normal,MI,0,1,0,1,1,0.62,0.58
745,745,745,745,11413,2019,Visakhapatnam,Visakhapatnam,SRH,1,DD,...,field,normal,DD,0,0,0,0,2,0.48,0.43
746,746,746,746,11414,2019,Visakhapatnam,Visakhapatnam,DD,1,CSK,...,field,normal,CSK,0,0,0,0,2,0.44,0.61

In [37]:
df = df[["TEAM1", "TEAM1_MODEL", "TEAM2", "TEAM2_MODEL", "TOSS_WINNER", "TOSS_WINNER_MODEL", "TEAM1_STRENGTH", "TEAM1_CUMU_STRENGTH", \
        "TEAM2_STRENGTH", "TEAM2_CUMU_STRENGTH", "WIN_RATE_TEAM1", "WIN_RATE_TEAM2", "WINNER", "WINNER_MODEL"]]

In [38]:
df

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
0,KKR,1,RCB,0,RCB,0,-0.23,-0.17,-1.16,-1.38,0.00,0.00,KKR,1
1,CSK,1,KXIP,0,CSK,1,-0.13,-0.04,-1.40,-1.69,0.00,0.00,CSK,1
2,DD,1,RR,0,RR,0,-0.85,-0.96,-0.62,-0.66,0.00,0.00,DD,1
3,RCB,1,MI,0,MI,0,-1.29,-1.52,0.17,0.39,0.00,0.00,RCB,1
4,KKR,1,SRH,0,SRH,0,-0.23,-0.17,-0.98,-1.14,1.00,0.00,KKR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,0.70,-0.04,0.05,0.31,0.62,0.47,KXIP,0
743,KKR,1,MI,0,MI,0,0.12,0.66,0.29,0.25,0.52,0.58,MI,0
744,CSK,1,MI,0,CSK,1,0.70,-0.04,0.29,0.25,0.62,0.58,MI,0
745,SRH,1,DD,0,DD,0,-0.55,0.49,2.24,-0.05,0.48,0.43,DD,0
746,DD,1,CSK,0,CSK,0,2.39,-0.15,0.67,0.06,0.44,0.61,CSK,0

In [39]:
df.drop(df[df["TEAM1"] == "KTK"].index, inplace = True) 
df.drop(df[df["TEAM2"] == "KTK"].index, inplace = True) 
df.drop(df[df["TEAM1"] == "GL"].index, inplace = True) 
df.drop(df[df["TEAM2"] == "GL"].index, inplace = True)

In [40]:
df

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
0,KKR,1,RCB,0,RCB,0,-0.23,-0.17,-1.16,-1.38,0.00,0.00,KKR,1
1,CSK,1,KXIP,0,CSK,1,-0.13,-0.04,-1.40,-1.69,0.00,0.00,CSK,1
2,DD,1,RR,0,RR,0,-0.85,-0.96,-0.62,-0.66,0.00,0.00,DD,1
3,RCB,1,MI,0,MI,0,-1.29,-1.52,0.17,0.39,0.00,0.00,RCB,1
4,KKR,1,SRH,0,SRH,0,-0.23,-0.17,-0.98,-1.14,1.00,0.00,KKR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,0.70,-0.04,0.05,0.31,0.62,0.47,KXIP,0
743,KKR,1,MI,0,MI,0,0.12,0.66,0.29,0.25,0.52,0.58,MI,0
744,CSK,1,MI,0,CSK,1,0.70,-0.04,0.29,0.25,0.62,0.58,MI,0
745,SRH,1,DD,0,DD,0,-0.55,0.49,2.24,-0.05,0.48,0.43,DD,0
746,DD,1,CSK,0,CSK,0,2.39,-0.15,0.67,0.06,0.44,0.61,CSK,0

### Modelling without using AHP

In [41]:
X = df[['TEAM1_MODEL', 'TEAM2_MODEL', 
       'TOSS_WINNER_MODEL', 'TEAM1_STRENGTH', 'TEAM1_CUMU_STRENGTH',
       'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH', 'WIN_RATE_TEAM1',
       'WIN_RATE_TEAM2']]
y = df["WINNER_MODEL"]

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=12)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 26.11it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
LinearSVC,0.57,0.58,0.58,0.57,0.05
RidgeClassifier,0.57,0.58,0.58,0.57,0.02
CalibratedClassifierCV,0.57,0.58,0.58,0.57,0.11
RidgeClassifierCV,0.57,0.58,0.58,0.57,0.00
LinearDiscriminantAnalysis,0.57,0.58,0.58,0.57,0.00
LogisticRegression,0.57,0.57,0.57,0.57,0.00
SGDClassifier,0.57,0.57,0.57,0.57,0.02
DecisionTreeClassifier,0.57,0.57,0.57,0.57,0.00
SVC,0.55,0.56,0.56,0.55,0.03
GaussianNB,0.55,0.56,0.56,0.53,0.02
PassiveAggressiveClassifier,0.55,0.55,0.55,0.55,0.02
ExtraTreesClassifier,0.55,0.55,0.55,0.55,0.15
Perceptron,0.52,0.55,0.55,0.44,0.02
NuSVC,0.54,0.55,0.55,0.54,0.03
BaggingClassifier,0.54,0.55,0.55,0.54,0.03
RandomForestClassifier,0.55,0.55,0.55,0.55,0.24
BernoulliNB,0.52,0.53,0.53,0.52,0.02
AdaBoostClassifier,0.52,0.53,0.53,0.53,0.10
XGBClassifier,0.51,0.51,0.51,0.51,0.07
LGBMClassifier,0.52,0.51,0.51,0.52,0.10
NearestCentroid,0.51,0.51,0.51,0.51,0.02
DummyClassifier,0.51,0.51,0.51,0.51,0.02
QuadraticDiscriminantAnalysis,0.46,0.50,0.50,0.29,0.02
CheckingClassifier,0.46,0.50,0.50,0.29,0.02
KNeighborsClassifier,0.49,0.50,0.50,0.48,0.02
LabelPropagation,0.49,0.49,0.49,0.49,0.02
ExtraTreeClassifier,0.50,0.49,0.49,0.50,0.00
LabelSpreading,0.48,0.49,0.49,0.48,0.03

In [42]:
df_ahp2 = df
df_ahp2

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL
0,KKR,1,RCB,0,RCB,0,-0.23,-0.17,-1.16,-1.38,0.00,0.00,KKR,1
1,CSK,1,KXIP,0,CSK,1,-0.13,-0.04,-1.40,-1.69,0.00,0.00,CSK,1
2,DD,1,RR,0,RR,0,-0.85,-0.96,-0.62,-0.66,0.00,0.00,DD,1
3,RCB,1,MI,0,MI,0,-1.29,-1.52,0.17,0.39,0.00,0.00,RCB,1
4,KKR,1,SRH,0,SRH,0,-0.23,-0.17,-0.98,-1.14,1.00,0.00,KKR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,0.70,-0.04,0.05,0.31,0.62,0.47,KXIP,0
743,KKR,1,MI,0,MI,0,0.12,0.66,0.29,0.25,0.52,0.58,MI,0
744,CSK,1,MI,0,CSK,1,0.70,-0.04,0.29,0.25,0.62,0.58,MI,0
745,SRH,1,DD,0,DD,0,-0.55,0.49,2.24,-0.05,0.48,0.43,DD,0
746,DD,1,CSK,0,CSK,0,2.39,-0.15,0.67,0.06,0.44,0.61,CSK,0

In [43]:
df_ahp2["AHP_RATIO_TEAM1"] = ''
df_ahp2["AHP_RATIO_TEAM2"] = ''


for i in range(0, 703):
    if df_ahp2["TEAM1"].iloc[i] == "CSK":
        df_ahp2["AHP_RATIO_TEAM1"].iloc[i] = 16.900712
    
    elif df_ahp2["TEAM1"].iloc[i] == "MI":
        df_ahp2["AHP_RATIO_TEAM1"].iloc[i] = 15.160852
    
    elif df_ahp2["TEAM1"].iloc[i] == "KKR":
        df_ahp2["AHP_RATIO_TEAM1"].iloc[i] = 12.745465
    
    elif df_ahp2["TEAM1"].iloc[i] == "RR":
        df_ahp2["AHP_RATIO_TEAM1"].iloc[i] = 12.695051
    
    elif df_ahp2["TEAM1"].iloc[i] == "RCB":
        df_ahp2["AHP_RATIO_TEAM1"].iloc[i] = 9.982425
    
    elif df_ahp2["TEAM1"].iloc[i] == "KXIP":
        df_ahp2["AHP_RATIO_TEAM1"].iloc[i] = 9.380131
    
    elif df_ahp2["TEAM1"].iloc[i] == "SRH":
        df_ahp2["AHP_RATIO_TEAM1"].iloc[i] = 9.026536
        
    elif df_ahp2["TEAM1"].iloc[i] == "DD":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 8.076035
    
    elif df_ahp2["TEAM1"].iloc[i] == "RPS":
        df_ahp1["AHP_RATIO_TEAM1"].iloc[i] = 6.032793
    
        
for i in range(0, 703):       
    if df_ahp2["TEAM2"].iloc[i] == "CSK":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 16.900712
        
    elif df_ahp2["TEAM2"].iloc[i] == "MI":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 15.160852
        
    elif df_ahp2["TEAM2"].iloc[i] == "KKR":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 12.745465
        
    elif df_ahp2["TEAM2"].iloc[i] == "RR":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 12.695051
        
    elif df_ahp2["TEAM2"].iloc[i] == "RCB":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 9.982425
        
    elif df_ahp2["TEAM2"].iloc[i] == "KXIP":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 9.380131
        
    elif df_ahp2["TEAM2"].iloc[i] == "SRH":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 9.026536
        
    elif df_ahp2["TEAM2"].iloc[i] == "DD":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 8.076035
        
    elif df_ahp2["TEAM2"].iloc[i] == "RPS":
        df_ahp2["AHP_RATIO_TEAM2"].iloc[i] = 6.032793

In [44]:
df_ahp2

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL,AHP_RATIO_TEAM1,AHP_RATIO_TEAM2
0,KKR,1,RCB,0,RCB,0,-0.23,-0.17,-1.16,-1.38,0.00,0.00,KKR,1,12.75,9.98
1,CSK,1,KXIP,0,CSK,1,-0.13,-0.04,-1.40,-1.69,0.00,0.00,CSK,1,16.90,9.38
2,DD,1,RR,0,RR,0,-0.85,-0.96,-0.62,-0.66,0.00,0.00,DD,1,,12.70
3,RCB,1,MI,0,MI,0,-1.29,-1.52,0.17,0.39,0.00,0.00,RCB,1,9.98,15.16
4,KKR,1,SRH,0,SRH,0,-0.23,-0.17,-0.98,-1.14,1.00,0.00,KKR,1,12.75,9.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,0.70,-0.04,0.05,0.31,0.62,0.47,KXIP,0,16.90,9.38
743,KKR,1,MI,0,MI,0,0.12,0.66,0.29,0.25,0.52,0.58,MI,0,12.75,15.16
744,CSK,1,MI,0,CSK,1,0.70,-0.04,0.29,0.25,0.62,0.58,MI,0,16.90,15.16
745,SRH,1,DD,0,DD,0,-0.55,0.49,2.24,-0.05,0.48,0.43,DD,0,9.03,8.08
746,DD,1,CSK,0,CSK,0,2.39,-0.15,0.67,0.06,0.44,0.61,CSK,0,,16.90

In [45]:
# df_ahp1.to_csv("innings_ahp_column.csv", index=False)

In [46]:
X = df_ahp1[['TEAM1_MODEL', 'TEAM2_MODEL', 
       'TOSS_WINNER_MODEL', 'TEAM1_STRENGTH', 'TEAM1_CUMU_STRENGTH',
       'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH', 'WIN_RATE_TEAM1',
       'WIN_RATE_TEAM2', 'AHP_RATIO_TEAM1', 'AHP_RATIO_TEAM2']]
y = df_ahp1["WINNER_MODEL"]

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=12)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 22.81it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
SGDClassifier,0.63,0.62,0.62,0.63,0.02
LGBMClassifier,0.62,0.62,0.62,0.62,0.10
BaggingClassifier,0.60,0.61,0.61,0.60,0.05
XGBClassifier,0.59,0.59,0.59,0.59,0.10
SVC,0.58,0.59,0.59,0.58,0.05
LogisticRegression,0.57,0.58,0.58,0.56,0.03
RidgeClassifier,0.57,0.58,0.58,0.56,0.02
BernoulliNB,0.57,0.58,0.58,0.58,0.02
ExtraTreesClassifier,0.57,0.57,0.57,0.57,0.14
RandomForestClassifier,0.57,0.57,0.57,0.57,0.22
CalibratedClassifierCV,0.56,0.57,0.57,0.55,0.11
ExtraTreeClassifier,0.57,0.57,0.57,0.57,0.02
RidgeClassifierCV,0.56,0.57,0.57,0.56,0.02
LinearSVC,0.56,0.57,0.57,0.56,0.04
LinearDiscriminantAnalysis,0.56,0.57,0.57,0.56,0.02
GaussianNB,0.56,0.57,0.57,0.56,0.02
NearestCentroid,0.57,0.57,0.57,0.57,0.02
KNeighborsClassifier,0.55,0.56,0.56,0.55,0.02
AdaBoostClassifier,0.56,0.56,0.56,0.56,0.11
QuadraticDiscriminantAnalysis,0.52,0.53,0.53,0.51,0.01
NuSVC,0.52,0.52,0.52,0.52,0.05
DummyClassifier,0.51,0.51,0.51,0.51,0.02
DecisionTreeClassifier,0.51,0.51,0.51,0.51,0.02
LabelSpreading,0.50,0.50,0.50,0.49,0.03
LabelPropagation,0.50,0.50,0.50,0.49,0.02
CheckingClassifier,0.46,0.50,0.50,0.29,0.01
Perceptron,0.48,0.50,0.50,0.46,0.01
PassiveAggressiveClassifier,0.46,0.46,0.46,0.46,0.02

## Dataset 2- Modelling 2

In [47]:
df_ahp2

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL,AHP_RATIO_TEAM1,AHP_RATIO_TEAM2
0,KKR,1,RCB,0,RCB,0,-0.23,-0.17,-1.16,-1.38,0.00,0.00,KKR,1,12.75,9.98
1,CSK,1,KXIP,0,CSK,1,-0.13,-0.04,-1.40,-1.69,0.00,0.00,CSK,1,16.90,9.38
2,DD,1,RR,0,RR,0,-0.85,-0.96,-0.62,-0.66,0.00,0.00,DD,1,,12.70
3,RCB,1,MI,0,MI,0,-1.29,-1.52,0.17,0.39,0.00,0.00,RCB,1,9.98,15.16
4,KKR,1,SRH,0,SRH,0,-0.23,-0.17,-0.98,-1.14,1.00,0.00,KKR,1,12.75,9.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,0.70,-0.04,0.05,0.31,0.62,0.47,KXIP,0,16.90,9.38
743,KKR,1,MI,0,MI,0,0.12,0.66,0.29,0.25,0.52,0.58,MI,0,12.75,15.16
744,CSK,1,MI,0,CSK,1,0.70,-0.04,0.29,0.25,0.62,0.58,MI,0,16.90,15.16
745,SRH,1,DD,0,DD,0,-0.55,0.49,2.24,-0.05,0.48,0.43,DD,0,9.03,8.08
746,DD,1,CSK,0,CSK,0,2.39,-0.15,0.67,0.06,0.44,0.61,CSK,0,,16.90

In [48]:
for i in range(0, 703):
    if df_ahp2["TEAM1"].iloc[i] == "CSK":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 1.521064
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.521064
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 1.521064
    
    elif df_ahp2["TEAM1"].iloc[i] == "MI":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 1.364477
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.364477
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 1.364477
    
    elif df_ahp2["TEAM1"].iloc[i] == "KKR":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 1.147092
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.147092
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 1.147092
    
    elif df_ahp2["TEAM1"].iloc[i] == "RR":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 1.142555
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 1.142555
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 1.142555
    
    elif df_ahp2["TEAM1"].iloc[i] == "RCB":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 0.898418
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.898418
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 0.898418
    
    elif df_ahp2["TEAM1"].iloc[i] == "KXIP":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 0.844212
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.844212
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 0.844212
    
    elif df_ahp2["TEAM1"].iloc[i] == "SRH":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 0.812388
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.812388
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 0.812388

    elif df_ahp2["TEAM1"].iloc[i] == "DD":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 0.726843
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.726843
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 0.726843
    
    elif df_ahp2["TEAM1"].iloc[i] == "RPS":
        df_ahp2["TEAM1_STRENGTH"].iloc[i] = df_ahp2["TEAM1_STRENGTH"].iloc[i] * 0.542951
        df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM1_CUMU_STRENGTH"].iloc[i] * 0.542951
        df_ahp2["WIN_RATE_TEAM1"].iloc[i] = df_ahp2["WIN_RATE_TEAM1"].iloc[i] * 0.542951
        

for i in range(0, 703):
    if df_ahp2["TEAM2"].iloc[i] == "CSK":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 1.521064
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.521064
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 1.521064
    
    elif df_ahp2["TEAM2"].iloc[i] == "MI":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 1.364477
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.364477
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 1.364477
    
    elif df_ahp2["TEAM2"].iloc[i] == "KKR":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 1.147092
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.147092
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 1.147092
    
    elif df_ahp2["TEAM2"].iloc[i] == "RR":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 1.142555
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 1.142555
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 1.142555
    
    elif df_ahp2["TEAM2"].iloc[i] == "RCB":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 0.898418
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.898418
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 0.898418
    
    elif df_ahp2["TEAM2"].iloc[i] == "KXIP":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 0.844212
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.844212
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 0.844212
    
    elif df_ahp2["TEAM1"].iloc[i] == "SRH":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 0.812388
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.812388
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 0.812388

    elif df_ahp2["TEAM1"].iloc[i] == "DD":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 0.726843
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.726843
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 0.726843
    
    elif df_ahp2["TEAM2"].iloc[i] == "RPS":
        df_ahp2["TEAM2_STRENGTH"].iloc[i] = df_ahp2["TEAM2_STRENGTH"].iloc[i] * 0.542951
        df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] = df_ahp2["TEAM2_CUMU_STRENGTH"].iloc[i] * 0.542951
        df_ahp2["WIN_RATE_TEAM2"].iloc[i] = df_ahp2["WIN_RATE_TEAM2"].iloc[i] * 0.542951

In [49]:
df_ahp2

,TEAM1,TEAM1_MODEL,TEAM2,TEAM2_MODEL,TOSS_WINNER,TOSS_WINNER_MODEL,TEAM1_STRENGTH,TEAM1_CUMU_STRENGTH,TEAM2_STRENGTH,TEAM2_CUMU_STRENGTH,WIN_RATE_TEAM1,WIN_RATE_TEAM2,WINNER,WINNER_MODEL,AHP_RATIO_TEAM1,AHP_RATIO_TEAM2
0,KKR,1,RCB,0,RCB,0,-0.26,-0.20,-1.04,-1.24,0.00,0.00,KKR,1,12.75,9.98
1,CSK,1,KXIP,0,CSK,1,-0.19,-0.06,-1.18,-1.43,0.00,0.00,CSK,1,16.90,9.38
2,DD,1,RR,0,RR,0,-0.62,-0.70,-0.71,-0.75,0.00,0.00,DD,1,,12.70
3,RCB,1,MI,0,MI,0,-1.16,-1.37,0.23,0.53,0.00,0.00,RCB,1,9.98,15.16
4,KKR,1,SRH,0,SRH,0,-0.26,-0.20,-0.98,-1.14,1.15,0.00,KKR,1,12.75,9.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,CSK,1,KXIP,0,KXIP,0,1.06,-0.05,0.04,0.26,0.95,0.39,KXIP,0,16.90,9.38
743,KKR,1,MI,0,MI,0,0.13,0.76,0.39,0.34,0.60,0.79,MI,0,12.75,15.16
744,CSK,1,MI,0,CSK,1,1.06,-0.05,0.39,0.34,0.94,0.79,MI,0,16.90,15.16
745,SRH,1,DD,0,DD,0,-0.44,0.40,1.82,-0.04,0.39,0.35,DD,0,9.03,8.08
746,DD,1,CSK,0,CSK,0,1.74,-0.11,1.02,0.09,0.32,0.94,CSK,0,,16.90

In [50]:
# df_ahp1.to_csv("innings_ahp_mean.csv", index=False)

In [51]:
X = df[['TEAM1_MODEL', 'TEAM2_MODEL', 
       'TOSS_WINNER_MODEL', 'TEAM1_STRENGTH', 'TEAM1_CUMU_STRENGTH',
       'TEAM2_STRENGTH', 'TEAM2_CUMU_STRENGTH', 'WIN_RATE_TEAM1',
       'WIN_RATE_TEAM2']]
y = df["WINNER_MODEL"]

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=12)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 28.31it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
CalibratedClassifierCV,0.62,0.62,0.62,0.62,0.08
LinearSVC,0.62,0.62,0.62,0.62,0.04
LinearDiscriminantAnalysis,0.62,0.62,0.62,0.62,0.02
RidgeClassifierCV,0.62,0.62,0.62,0.62,0.01
RidgeClassifier,0.62,0.62,0.62,0.62,0.01
LogisticRegression,0.62,0.62,0.62,0.62,0.01
NearestCentroid,0.62,0.62,0.62,0.62,0.01
SVC,0.60,0.61,0.61,0.60,0.02
GaussianNB,0.58,0.59,0.59,0.57,0.02
BernoulliNB,0.58,0.59,0.59,0.58,0.02
Perceptron,0.57,0.58,0.58,0.57,0.01
AdaBoostClassifier,0.57,0.57,0.57,0.57,0.09
LGBMClassifier,0.57,0.57,0.57,0.57,0.10
ExtraTreesClassifier,0.56,0.57,0.57,0.56,0.13
PassiveAggressiveClassifier,0.56,0.57,0.57,0.56,0.01
XGBClassifier,0.56,0.56,0.56,0.56,0.08
BaggingClassifier,0.55,0.56,0.56,0.55,0.04
KNeighborsClassifier,0.55,0.56,0.56,0.55,0.01
NuSVC,0.55,0.56,0.56,0.55,0.04
RandomForestClassifier,0.54,0.54,0.54,0.54,0.22
DummyClassifier,0.51,0.51,0.51,0.51,0.02
QuadraticDiscriminantAnalysis,0.46,0.50,0.50,0.29,0.01
CheckingClassifier,0.46,0.50,0.50,0.29,0.02
DecisionTreeClassifier,0.50,0.50,0.50,0.50,0.00
LabelSpreading,0.49,0.49,0.49,0.49,0.03
LabelPropagation,0.49,0.49,0.49,0.49,0.02
SGDClassifier,0.47,0.47,0.47,0.47,0.02
ExtraTreeClassifier,0.43,0.44,0.44,0.43,0.00